name: The Stubborn Stain
favicon: null
layout_spectrum: 0.22667
typography_spectrum: 0.08705
title: The Stubborn Stain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbd8e1'
    - '#89aad5'
    - '#101221'
    - '#584e4c'
    - '#d99976'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
