name: The Stubborn Stain
favicon: null
layout_spectrum: 0.03651134157553315
typography_spectrum: 0.3362258360721171
title: The Stubborn Stain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9152557621710002
  lightness: 0.09841235005296767
  saturation: 0.47467975481413305
  rhythmicContrast: 0.3345726311672479
purpose: []
